//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Arme
	{
		private int id;

		private string nom;

		private int puissance;

		public Arme(int id, string nom, int puissance)
		{
		}

		public virtual string GetNom()
		{
			throw new System.NotImplementedException();
		}

		public virtual int GetPuissance()
		{
			throw new System.NotImplementedException();
		}

		public virtual int GetId()
		{
			throw new System.NotImplementedException();
		}

	}
}

