//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Arme
	{
		private int id;

		private string nom;

		private int puissance;

		public Arme(int id, string nom, int puissance)
		{
            if (id<=0)
            {
                throw new ArgumentOutOfRangeException("ERREUR : ID négatif");
            }
            else this.id = id;

            if (String.IsNullOrWhiteSpace(nom) || String.IsNullOrEmpty(nom) || !Char.IsLetter(nom[0]))
            {
                throw new ArgumentOutOfRangeException("ERREUR : Nom vide");
            }
            else this.nom = nom;

            if(puissance<0)
            {
                throw new ArgumentOutOfRangeException("ERREUR: Puissance négative");
            }else this.puissance = puissance;

		}

		public virtual string GetNom()
		{
            return this.nom;
		}

		public virtual int GetPuissance()
		{
            return this.puissance;
		}

		public virtual int GetId()
		{
            return this.id;
		}

	}
}

