//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Chasseur : Personnage
	{
		private static string c_type;

		private string fonction;

		private static int c_force = 20;

        private List<Arme> mesArmes;

		public override void RecevoirArme(Arme a)
		{
            mesArmes.Add(a);
		}

		public override string PresentationCourte()
		{
			throw new System.NotImplementedException();
		}

		public override string PresentationDetail()
		{
			throw new System.NotImplementedException();
		}

		public virtual void ListerMesArmes()
		{
			throw new System.NotImplementedException();
		}

		public static string c_GetTypePers()
		{
			throw new System.NotImplementedException();
		}

		public Chasseur(string nom, string fonction)
		{
		}

		public override int GetForce()
		{
			throw new System.NotImplementedException();
		}

		public static void c_SetTypePers()
		{
			throw new System.NotImplementedException();
		}

		public virtual string GetFonction()
		{
			throw new System.NotImplementedException();
		}

		public static void c_SetForce()
		{
			throw new System.NotImplementedException();
		}

	}
}

