//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Chasseur : Personnage
	{
		private static string c_type;

		private string fonction;

		private static int c_force = 20;

        private List<Arme> mesArmes;

		public override void RecevoirArme(Arme a)
		{
            mesArmes.Add(a);
		}

		public override string PresentationCourte()
		{
            string pres = base.PresentationCourte();
            pres += string.Format("{2,-10}{3,-6}{4,-6}{5,-16}{6,-8}", Chasseur.c_type, this.GetForce(), this.GetVie(), this.fonction, this.mesArmes.Count);
            return pres;
		}

		public override string PresentationDetail()
		{
            string pres = base.PresentationDetail();
            pres += string.Format("{2,-10}{3,-6}{4,-6}{5,-16}{6,-8}", Chasseur.c_type, this.GetForce(), this.GetVie(), this.fonction, this.mesArmes.Count);
            return pres;
		}

		public virtual void ListerMesArmes()
		{
			foreach (Arme a in this.mesArmes)
            {
                Console.Write(a.GetNom() + "  ");
            }
		}

		public static string c_GetTypePers()
		{
            return Chasseur.c_type;
		}

		public Chasseur(string nom, string fonction, int id) : base(nom,Personnage.c_vieNaissance, id)
		{
            this.fonction = fonction;
		}

		public override int GetForce()
		{
            return Chasseur.c_force;
		}

		public static void c_SetTypePers(string type)
		{
            Chasseur.c_type = type;
		}

		public virtual string GetFonction()
		{
            return this.fonction;
		}

		public static void c_SetForce(int force)
		{
            Chasseur.c_force = force;
		}

	}
}

