//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class G_Armes
	{
        public static IDictionary<int, Arme> ListeArmes;
        

		public static Arme CreerUneArme(int id, string nom, int puissance)
		{
            Arme nouvelleArme = new Arme(id, nom, puissance);
            G_Armes.ListeArmes.Add(id,nouvelleArme);
            return nouvelleArme;
		}

        public static Arme GetArme(int id)
        {
            foreach (Arme a in ListeArmes)
            {
                if (a.GetId() == id)
                {
                    return a;
                }
            }
            throw new IndexOutOfRangeException("L'arme n'existe pas!");
        }

		public static IEnumerable<Arme> ListerTtesArmes()
		{
            List<Arme> liste = new List<Arme>();

            foreach(KeyValuePair<int,Arme> a in G_Armes.ListeArmes)
            {
                liste.Add(a.Value);
            }
            return liste ;
		}

	}
}

