//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class G_Armes
	{
        public static List<Arme> ListeArmes;
        

		public static Arme CreerUneArme(int id, string nom, int puissance)
		{
            Arme nouvelleArme = new Arme(id, nom, puissance);
            G_Armes.ListeArmes.Add(nouvelleArme);
            return nouvelleArme;
		}

		public static List<Arme> ListerTtesArmes()
		{
            return G_Armes.ListeArmes;
		}

	}
}

