//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Personnage
	{
		private string nom;

		private int vie = 200;

		private int id;

		protected static int c_vieNaissance = 200;

        private List<Personnage> mesEnnemis;

		public abstract void RecevoirArme(Arme a);

		public virtual void Frapper(Personnage victime)
		{
            victime.RecevoirCoup(this, this.GetForce());
            this.mesEnnemis.Add(victime);
		}

		public abstract string GetTypePers();

		public virtual string PresentationCourte()
		{
            return String.Format("{0,-4}{1,-4}", this.id, this.nom);
		}

		public virtual string PresentationDetail()
		{
            return this.PresentationCourte() + "\n ennemis : " + this.GetEnnemis();
		}

		public abstract IEnumerable<Arme> GetListeArmes();

		public virtual int GetId()
		{
            return this.id;
		}

		public virtual string GetName()
		{
            return this.nom;
		}

		public abstract int GetForce();

        public abstract string ListerMesArmes();

		public virtual int GetVie()
		{
            return this.vie;
		}

		public Personnage(string nom, int vie, int id)
		{
            this.nom = nom;
            this.vie = vie;
            this.id = id;
            
            this.mesEnnemis = new List<Personnage>();
		}

		public abstract void SetTypePers(string type);

		public virtual void RecevoirCoup(Personnage agresseur, int force)
		{
            this.mesEnnemis.Add(agresseur);
            this.vie -= force;
		}

        public string GetEnnemis()
        {
            string ennemis = "";
            foreach(Personnage p in mesEnnemis)
            {
                ennemis += p.nom + " ";
            }
            return ennemis;
        }
		
		public ICollection<Personnage> GetListeEnnemis() {
			return new List<Personnage>(mesEnnemis);
		}
		
		public void AjouterEnnemi(Personnage p) {
			this.mesEnnemis.Add(p);
		}
	}
}