//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Troll : Personnage
	{
		private static string c_type = "Troll";

		private int taille;
		private int force;

        public override string PresentationCourte()
        {
            return String.Format(base.PresentationCourte() + "{0,-10}{1,-6}{2,-6}{3,-16}", this.GetTypePers(), this.GetForce(), this.GetVie(), this.taille);
        }

		public override string PresentationDetail()
		{
            //return this.PresentationCourte() + "ennemis : " + this.GetEnnemis();
            return base.PresentationDetail();
		}

		public override void RecevoirArme(Arme a)
		{
            Console.WriteLine("Un Troll ne peut pas d'arme !");
		}

		public override IEnumerable<Arme> GetListeArmes()
		{
            Console.WriteLine("Un Troll n'a pas d'armes !");
            return null;
		}

		public override string GetTypePers()
		{
            return c_type;
		}

		public Troll(int id, string nom, int taille, int force) : base(id, nom, Personnage.c_vieNaissance)
		{
            if (taille < 0)
            {
                throw new ArgumentOutOfRangeException("La taille d'un Troll ne peux pas être < 0");
            }
            else this.taille = taille;

            if (force < 0)
            {
                throw new ArgumentOutOfRangeException("La force d'un Troll ne peux pas être < 0");
                
            }
            else this.force = force;
		}

		public override int GetForce()
		{
            return this.force;
           
		}

        public override string ListerMesArmes()
        {
            return "";
        }

		public override void SetTypePers(string type)
		{
            Troll.c_type = type;
		}

		public virtual int GetTaille()
		{
            return this.taille;
		}

	}
}

