//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Troll : Personnage
	{
		private int taille;

		private static string c_type;

		private int force;

		public override string PresentationCourte()
		{
			throw new System.NotImplementedException();
		}

		public override string PresentationDetail()
		{
			throw new System.NotImplementedException();
		}

		public override void RecevoirArme(Arme a)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ListerMesArmes()
		{
			throw new System.NotImplementedException();
		}

		public static string c_GetTypePers()
		{
			throw new System.NotImplementedException();
		}

		public Troll(string nom, int taille, int force) : base(nom, Personnage.c_vieNaissance)
		{
		}

		public override int GetForce()
		{
			throw new System.NotImplementedException();
		}

		public static void c_SetTypePers()
		{
			throw new System.NotImplementedException();
		}

		public virtual int GetTaille()
		{
			throw new System.NotImplementedException();
		}

	}
}

