//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Troll : Personnage
	{
		private int taille;

		private static string c_type;

		private int force;

		public override string PresentationCourte() 
		{
            return String.Format(base.PresentationCourte() + "{2,-10}{3,-6}{4,-6}{5,-16}", this.GetTypePers(), this.GetForce(), this.GetVie(), this.taille);
		}

		public override string PresentationDetail()
		{
            return String.Format(base.PresentationCourte() + "{2,-10}{3,-6}{4,-6}{5,-16}", this.GetTypePers(), this.GetForce(), this.GetVie(), this.taille);
		}

		public override void RecevoirArme(Arme a)
		{
            Console.WriteLine("Un Troll ne peut pas recevoir d'arme !");
		}

		public virtual void ListerMesArmes()
		{
            Console.WriteLine("Un Troll n'a pas d'armes !");
		}

		public static string c_GetTypePers()
		{
            return c_type;
		}

		public Troll(string nom, int taille, int force, int id) : base(nom, Personnage.c_vieNaissance, id)
		{
            this.force = force;
		}

		public override int GetForce()
		{
            return this.force;
           
		}

		public static void c_SetTypePers(string type)
		{
            c_type = type;
		}

		public virtual int GetTaille()
		{
            return this.taille;
		}

	}
}

