//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Facade
	{
		public virtual void InitialiserJeuVide()
		{
			throw new System.NotImplementedException();
		}

		public virtual void CreerJeuDEssai()
		{
			throw new System.NotImplementedException();
		}

		public virtual Troll AjouterTroll(string nom, string taille, int force)
		{
			throw new System.NotImplementedException();
		}

		public virtual void AjouterChasseur(string nom, string fonction)
		{
			throw new System.NotImplementedException();
		}

		public virtual Arme CreerUneArme(int id, string nom, int puissance)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DonnerUneArme(int idA, int idP)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Frapper(int idAgresseur, int idVictime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SupprimerPers(int id)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<string> AfficherArmesDispo()
		{
			throw new System.NotImplementedException();
		}

		public virtual string AfficherPersonnageDc(int id)
		{
			throw new System.NotImplementedException();
		}

		public virtual string AfficherPersonnageDd(int id)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<string> AfficherTsPersonnagesDc()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<string> AfficherTsPersonnagesDd()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<Personne> ListerTsPersonnages()
		{
			throw new System.NotImplementedException();
		}

		public virtual Personnage getPersonnage(int id)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<Arme> ListerTtesArmes()
		{
			throw new System.NotImplementedException();
		}

		public virtual Arme GetArme(int id)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<Armes> GetArmes(int idPers)
		{
			throw new System.NotImplementedException();
		}

	}
}

