//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class G_Armes
	{
		public virtual IEnumerable<Arme> ListeArmes
		{
			get;
			set;
		}

		public static Arme CreerUneArme(int id, string nom, int puissance)
		{
			throw new System.NotImplementedException();
		}

		public static IEnumerable<Arme> ListerTtesArmes()
		{
			throw new System.NotImplementedException();
		}

	}
}

