//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace packTrolls
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Personnage
	{
		private static int nextId = 0;

		private string nom;

		private int vie = 200;

		private int id;

		protected static int c_vieNaissance = 200;

        private List<Personnage> mesEnnemis;

		public abstract void RecevoirArme(Arme a);

		public virtual void Frapper(Personnage victime)
		{
			throw new System.NotImplementedException();
		}

		public abstract string GetTypePers();

		public virtual string PresentationCourte()
		{
			throw new System.NotImplementedException();
		}

		public virtual string PresentationDetail()
		{
			throw new System.NotImplementedException();
		}

		public abstract IEnumerable<Arme> ListerMesArmes();

		public virtual int GetId()
		{
			throw new System.NotImplementedException();
		}

		public virtual string GetName()
		{
			throw new System.NotImplementedException();
		}

		public abstract int GetForce();

		public virtual int GetVie()
		{
			throw new System.NotImplementedException();
		}

		public Personnage(string nom, int vie)
		{
            this.nom = nom;
            this.vie = vie;
		}

		public abstract void SetTypePers();

		public virtual void RecevoirCoup(Personnage agresseur, int force)
		{
			throw new System.NotImplementedException();
		}
	}
}

